# Generated by Django 5.0.6 on 2024-06-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
